spring.application.name=extractly
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.session.jdbc.initialize-schema=always

gemini.api.key=${GEMINI_API_KEY}

zoho.clientID = ${ZOHO_CLIENT_ID}
zoho.clientSecret = ${ZOHO_CLIENT_SECRET}
zoho.refreshToken = ${ZOHO_REFRESH_TOKEN}
zoho.baseAccountUrl = ${ZOHO_BASE_ACCOUNT_URL}