spring.application.name=extractly
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.session.jdbc.initialize-schema=always

gemini.api.key=${GEMINI_API_KEY}
assemblyai.api.key=${ASSEMBLYAI_API_KEY}

zoho.clientID = ${ZOHO_CLIENT_ID}
zoho.clientSecret = ${ZOHO_CLIENT_SECRET}
zoho.refreshToken = ${ZOHO_REFRESH_TOKEN}
zoho.baseAccountUrl = ${ZOHO_BASE_ACCOUNT_URL}

zoho.api_url = ${ZOHO_API_URL}
zoho.accountOwnerName = ${ZOHO_ACCOUNT_OWNER}
zoho.appLinkName = ${ZOHO_APP_LINK_NAME}
zoho.formLinkName = ${ZOHO_FORM_LINK_NAME}
zoho.reportLinkName = ${ZOHO_REPORT_LINK_NAME}

spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
cloudinary.url=${CLOUDINARY_URL}

# spring.mail.host=smtp.zoho.com
# spring.mail.port=587
# spring.mail.username=${ZOHO_SMTP_EMAIL}
# spring.mail.password=${ZOHO_SMTP_APP_PASSWORD}
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

# app.baseUrl=${APP_BASE_URL:http://localhost:8080}